using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace FastInject
{
    /// <summary>
    /// A source generator that automatically registers classes for Dependency Injection 
    /// based on custom attributes ([Scoped], [Transient], [Singleton]).
    /// </summary>
    [Generator]
    public class DependencyInjectionGenerator : IIncrementalGenerator
    {
        public void Initialize(IncrementalGeneratorInitializationContext context)
        {
            // STEP 1: Inject the required attributes into the target project automatically.
            // This ensures the library is "zero-dependency" for the consumer.
            context.RegisterPostInitializationOutput(ctx => ctx.AddSource(
                "FastInjectAttributes.g.cs",
                SourceText.From(@"// <auto-generated />
using System;

namespace FastInject
{
    [AttributeUsage(AttributeTargets.Class, Inherited = false, AllowMultiple = false)]
    public sealed class ScopedAttribute : Attribute { public Type InterfaceType { get; } public ScopedAttribute(Type type) { InterfaceType = type; } }

    [AttributeUsage(AttributeTargets.Class, Inherited = false, AllowMultiple = false)]
    public sealed class TransientAttribute : Attribute { public Type InterfaceType { get; } public TransientAttribute(Type type) { InterfaceType = type; } }

    [AttributeUsage(AttributeTargets.Class, Inherited = false, AllowMultiple = false)]
    public sealed class SingletonAttribute : Attribute { public Type InterfaceType { get; } public SingletonAttribute(Type type) { InterfaceType = type; } }
}", Encoding.UTF8)));

            // STEP 2: Create a SyntaxProvider to find classes with attributes.
            // We first filter syntactically (fast), then transform semantically (slower, but accurate).
            var classProvider = context.SyntaxProvider
                .CreateSyntaxProvider(
                    predicate: static (s, _) => s is ClassDeclarationSyntax c && c.AttributeLists.Count > 0,
                    transform: static (ctx, _) => GetClassWithInjectAttribute(ctx))
                .Where(static t => t != null);

            // STEP 3: Register the source output to generate the extension method 
            // once all matching classes are collected.
            context.RegisterSourceOutput(
                context.CompilationProvider.Combine(classProvider.Collect()),
                (ctx, source) => Execute(ctx, source.Right));
        }

        /// <summary>
        /// Analyzes the semantic model to verify if the class actually contains 
        /// the specific FastInject attributes.
        /// </summary>
        private static INamedTypeSymbol? GetClassWithInjectAttribute(GeneratorSyntaxContext context)
        {
            var classDeclaration = (ClassDeclarationSyntax)context.Node;

            // Get the semantic symbol for the class
            var symbol = context.SemanticModel.GetDeclaredSymbol(classDeclaration) as INamedTypeSymbol;
            if (symbol == null) return null;

            // Iterate through the attributes to find a match belonging to the FastInject namespace
            foreach (var attribute in symbol.GetAttributes())
            {
                var attrName = attribute.AttributeClass?.Name;
                if ((attrName == "ScopedAttribute" || attrName == "TransientAttribute" || attrName == "SingletonAttribute") &&
                    attribute.AttributeClass?.ContainingNamespace.ToDisplayString() == "FastInject")
                {
                    return symbol; // Found a valid attribute, return the class symbol
                }
            }
            return null; // No matching attribute found
        }

        /// <summary>
        /// Generates the DependencyInjectionExtensions class containing the AddFastInjectServices method.
        /// </summary>
        private static void Execute(SourceProductionContext context, ImmutableArray<INamedTypeSymbol?> symbols)
        {
            // If no classes were found with our attributes, do nothing
            if (symbols.IsDefaultOrEmpty) return;

            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated />");
            sb.AppendLine("using Microsoft.Extensions.DependencyInjection;");
            sb.AppendLine();
            sb.AppendLine("namespace FastInject.Extensions");
            sb.AppendLine("{");
            sb.AppendLine("    public static class DependencyInjectionExtensions");
            sb.AppendLine("    {");
            sb.AppendLine("        /// <summary>");
            sb.AppendLine("        /// Automatically registers all services marked with FastInject attributes.");
            sb.AppendLine("        /// </summary>");
            sb.AppendLine("        public static IServiceCollection AddFastInjectServices(this IServiceCollection services)");
            sb.AppendLine("        {");

            // Loop through each unique class symbol found
            foreach (var symbol in symbols.Distinct(SymbolEqualityComparer.Default).Cast<INamedTypeSymbol>())
            {
                // Find the specific FastInject attribute applied to this class
                var attribute = symbol.GetAttributes().First(a =>
                    a.AttributeClass?.Name == "ScopedAttribute" ||
                    a.AttributeClass?.Name == "TransientAttribute" ||
                    a.AttributeClass?.Name == "SingletonAttribute");

                // Extract the interface type provided in the attribute constructor (e.g., typeof(IUserService))
                var interfaceType = attribute.ConstructorArguments.FirstOrDefault().Value as INamedTypeSymbol;

                if (interfaceType != null)
                {
                    // Get the fully qualified names for the implementation and the interface
                    var implementationName = symbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
                    var interfaceName = interfaceType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);

                    // Determine the correct DI method based on the attribute name
                    string lifetimeMethod = attribute.AttributeClass!.Name switch
                    {
                        "TransientAttribute" => "AddTransient",
                        "SingletonAttribute" => "AddSingleton",
                        _ => "AddScoped"
                    };

                    // Generate the service registration line
                    sb.AppendLine($"            services.{lifetimeMethod}<{interfaceName}, {implementationName}>();");
                }
            }

            sb.AppendLine("            return services;");
            sb.AppendLine("        }");
            sb.AppendLine("    }");
            sb.AppendLine("}");

            // Add the generated source code to the compilation
            context.AddSource("FastInjectExtensions.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
        }
    }
}